workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      node: latest
      java: 17
      android:
        image: default
    scripts:
      - rm -rf node_modules
      - npm ci || npm install
      - npx --yes @capacitor/cli@latest sync android
      - chmod +x android/gradlew
      - cd android
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
