workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - npm install
      - npx cap sync android
      - cd android
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
