name: Build Android APKs (Debug & Release)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || npm install

      - name: Ensure Capacitor CLI
        run: npm install -g @capacitor/cli@7.4.2

      - name: Prepare Android project (add if missing) and sync
        run: |
          if [ ! -d android ]; then npx --yes @capacitor/cli@7.4.2 add android; fi
          npx --yes @capacitor/cli@7.4.2 copy android
          npx --yes @capacitor/cli@7.4.2 sync android

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew

      - name: Build Debug & Release APKs
        working-directory: android
        run: ./gradlew assembleDebug assembleRelease

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-outputs
          path: |
            android/app/build/outputs/apk/debug/*.apk
            android/app/build/outputs/apk/release/*.apk
